# Generated by Django 3.2.4 on 2021-07-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('startapp', 'Startupper'), ('worker', 'Practical worker'), ('dev', 'Developer')], max_length=20, null=True)),
                ('skills', models.TextField(max_length=1000, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('resume', models.FileField(upload_to='')),
            ],
        ),
    ]
