# Generated by Django 3.2.4 on 2021-07-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210705_0906'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_details',
        ),
        migrations.AddField(
            model_name='prog_level',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prog_level',
            name='resume',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='prog_level',
            name='skills',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='level',
            field=models.CharField(choices=[('practice', 'Practical worker'), ('startup', 'Startupper'), ('developer', 'Developer')], max_length=20),
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='project',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
