# Generated by Django 3.2.4 on 2021-07-05 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210705_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prog_level',
            name='level',
            field=models.CharField(choices=[('practice', 'Practical worker'), ('startup', 'Startupper'), ('developer', 'Developer')], max_length=20, null=True),
        ),
    ]
