# Generated by Django 3.2.4 on 2021-07-05 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210705_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='prog_level',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prog_level',
            name='type_work',
            field=models.CharField(choices=[('Offline', 'Offline'), ('Online', 'Online')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='level',
            field=models.CharField(choices=[('practice', 'Practical worker'), ('developer', 'Developer')], max_length=20, null=True),
        ),
    ]
