# Generated by Django 3.2.4 on 2021-07-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210705_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prog_level',
            name='image',
        ),
        migrations.AddField(
            model_name='prog_level',
            name='avatar',
            field=models.ImageField(null=True, upload_to='avatar'),
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='project',
            field=models.FileField(null=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='prog_level',
            name='resume',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
