# Generated by Django 3.2.4 on 2021-07-06 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210707_0220'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='password1',
            field=models.CharField(max_length=200, null=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='password2',
            field=models.CharField(max_length=200, null=True, verbose_name='password confirm'),
        ),
        migrations.CreateModel(
            name='Startapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('project', models.FileField(default='No bio...', null=True, upload_to='project')),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('project', models.FileField(default='No bio...', null=True, upload_to='project')),
                ('comment', models.TextField(max_length=2000, null=True)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='IdeaStartapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='startapper_idea')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.startapper')),
            ],
        ),
    ]
