# Generated by Django 3.2.4 on 2021-07-07 00:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0014_auto_20210707_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('project', models.FileField(null=True, upload_to='project')),
                ('comment', models.TextField(default='No comment...', max_length=2000, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('programming_language', models.CharField(choices=[('startap', 'Startupper'), ('practice', 'Practitioner'), ('developer', 'Developer')], default='developer', max_length=20)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Practitioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('project', models.FileField(null=True, upload_to='project')),
                ('comment', models.TextField(default='No comment...', max_length=2000, null=True)),
                ('number', models.CharField(max_length=20, null=True)),
                ('skills', models.CharField(max_length=200, null=True)),
                ('programming_language', models.CharField(choices=[('startap', 'Startupper'), ('practice', 'Practitioner'), ('developer', 'Developer')], default='practice', max_length=20)),
                ('avatar', models.ImageField(null=True, upload_to='avatar')),
                ('resume', models.FileField(null=True, upload_to='resume')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
        migrations.AlterField(
            model_name='startapper',
            name='comment',
            field=models.TextField(default='No comment...', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='startapper',
            name='project',
            field=models.FileField(null=True, upload_to='project'),
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
    ]
