# Generated by Django 3.2.4 on 2021-07-07 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20210707_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startapper',
            name='number',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
