# Generated by Django 3.2.4 on 2021-07-07 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20210708_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='startapper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
    ]
