# Generated by Django 3.2.4 on 2021-07-07 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20210708_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('startap', 'Startupper'), ('practice', 'Practitioner'), ('developer', 'Developer')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='practitioner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
        migrations.AlterField(
            model_name='startapper',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.customuser'),
        ),
    ]
